### ISSUE TITLE
reporter fails (CRAN checks) in R-devel: Should use `format(.)`, not `as.character(.)`

### ISSUE THREAD

**Issue by mmaechler** [dbosak01/reporter#269]
See   https://cloud.r-project.org/web/checks/check_results_reporter.html

It is really only in your   `render.pdf_info()` function where you use  __3 times__  `as.character(tm, <format>)`
and you should use  `format( .... )`  instead of as.character().

Best regards,
Martin Mächler

**Comment by dbosak01** [comment]
Thanks! 

 

From: Martin Mächler ***@***.***> 
Sent: Thursday, October 6, 2022 10:50 AM
To: dbosak01/reporter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dbosak01/reporter] reporter fails (CRAN checks) in R-devel: Should use `format(.)`, not `as.character(.)` (Issue #269)

 

See https://cloud.r-project.org/web/checks/check_results_reporter.html

It is really only in your render.pdf_info() function where you use 3 times as.character(tm, <format>)
and you should use format( .... ) instead of as.character().

Best regards,
Martin Mächler
