### ISSUE TITLE
Add a parameter in write_report to control console output

### ISSUE THREAD

**Issue by Jean-Maupas** [dbosak01/reporter#320]
When using markdown (and probably Jupyter and similar tools) for generating reports, the write_report statement generates a text output providing a lot of details. It is displayed after the code chunk like any console output.
Although this log could be useful in production (maybe it would be better redirected to logr if a log is opened), it would be great if we could instead display the table as TXT while in development, i.e. adding a parameter to write_report as console_output = c("log", "table", "both", "summary", "none") with "log" as default.  
Depending on the development stage, we could switch between  [console_output="table", preview=1] and [console_output="log", preview=NULL]. 
"none" or "summary" would be interesting when generating several formats (typically RTF and PDF) of the same table; "summary"  would not output the details of the table and could be used for subsequent generations.  
This shouldn't change the file creation itself, just what happens in the console. 
When "table" is selected, we could display it in rstudio Viewer.

**Comment by dbosak01** [comment]
You can prevent writing to the console by sending the result to a variable.  Like this:

![image](https://github.com/dbosak01/reporter/assets/41754982/a2372e31-f501-4d48-9f95-788c64afa032)

The write_report() output does go to the logr log automatically, if it is open and the autolog feature is turned on.  If you don't want it to go to the log, you can turn it off with `log = FALSE` on `write_report()`, or turn off autolog.    

For the "table" option, there is the `proc_print()` function from the procs package.  This will send any data frame to the viewer.  It won't show the entire report, but you can at least see the data.

These comments somewhat address everything except the "summary" option.  Don't have anything like that currently. Will consider.

**Comment by dbosak01** [comment]
What is the point of the RMD?  Are you trying to get several TFLs into the same document, or are you creating an SAP or CSR where you are combining the tables with some other content?

**Comment by Jean-Maupas** [comment]
I'm using it like a notebook (like I use Jupyter with python), mainly as a
reporting tool for ad-hoc analysis or other clinical presentations for
conferences or internally (board...). Usually a lot of graphs and small
tables, but it's always good to link or integrate the full corresponding
listings, so people could check etc... We are currently complementing some
CRO deliverables and Reporter helped us to easily keep the same format.
So, to answer your question, I guess that's a little of both.

**Comment by dbosak01** [comment]
I see.  What you need is issue #161.  The idea was to stream the table content back without creating a written file.  I can create both text and HTML reports.  But with the current functionality I don't know how to get them back to the RMD nicely.  Let me play with this and see what I can come up with.  Also I can look at #161 again and see how hard it is to implement.  If it is not too hard, I can do it over winter break.

**Comment by dbosak01** [comment]
This was an interesting experiment.  Thanks for making me explore it.  I was able to get the HTML into the RMD pretty cleanly using the `includeHTML()` function from htmltools.  Example attached.  
[MyDoc.txt](https://github.com/dbosak01/reporter/files/13574503/MyDoc.txt)
And here is what I'm getting:

![image](https://github.com/dbosak01/reporter/assets/41754982/54207be1-f659-44eb-a235-adc5bbaa57a9)

There might be some interference with the style sheets.  But this will at least get you started.

**Comment by dbosak01** [comment]
Got it.  The page_header object always aligns to the container, either a page or browser.  But the titles can align to the container, the content, or a specific width.  Check out the "width" parameter on the `titles()` function.  If you attach the titles to the content, by default they will align to the content they are attached to.  Also, you can put multiple titles on an object.  Also there is a "columns" parameter that allows you to split the titles into 1 to 3 columns.  All this means you can achieve what you are trying to do by putting the page header information in a separate `titles()` function instead of the `page_header()` function.  Then set the columns to 2 and put your page header strings in there.

Here is what it looks like:

![image](https://github.com/dbosak01/reporter/assets/41754982/e0ff3ded-0274-47b8-9414-785e5f2edc1a)


And here is the code: 

[MyDoc2.txt](https://github.com/dbosak01/reporter/files/13606240/MyDoc2.txt)

Note that for footnotes, you'll also want to attach them to the content, and don't use the `page_footer()`.  Otherwise, you'll get a bunch of blank spaces.
