### ISSUE TITLE
Page header and page footer displaying issue in html

### ISSUE THREAD

**Issue by Raphael0522** [dbosak01/reporter#334]
Hi David, I was trying to output table result in html. The page header and page footer are displayed much longer than the contents. I guess the width are assigned as different values in table elements. Please take a look when you get a chance. Thanks.

![image](https://github.com/dbosak01/reporter/assets/19573521/de1ff96d-084a-4c47-b9b9-e2e61634a569)

**Comment by dbosak01** [comment]
That's correct.  When viewed interactively, it goes the full width of the browser.  If you make the browser more narrow, the page header and footer will also narrow.  When you print it, everything will align to the page size.  Hope this makes sense.  You can force it to be a specific width by putting the header and footer in titles and footnotes blocks instead of page_header and page_footer functions.  Then you can use the width property to set it as wide as you want.

**Comment by Raphael0522** [comment]
Hi David, I got your point. Thanks for your clarification.

Best regards,
Raphael
